name: 🚀 Release

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: 🏷️ Create Release
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    
    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}
    
    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm test

      - name: 🏗️ Build project
        run: npm run build

      - name: 🏷️ Create Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 22
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-preview:
    name: 🚀 Deploy Preview
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.released == 'true'
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🏗️ Build for preview
        run: npm run build
        env:
          NODE_ENV: production

      - name: 🚀 Deploy to preview
        id: deploy
        run: |
          echo "url=https://preview-${{ needs.release.outputs.version }}.example.com" >> $GITHUB_OUTPUT
          # Ici vous ajouteriez votre logique de déploiement
          # Par exemple : deploiement vers Vercel, Netlify, AWS, etc.

  notify-success:
    name: 📢 Notify Success
    runs-on: ubuntu-latest
    needs: [release, deploy-preview]
    if: always() && needs.release.outputs.released == 'true'
    
    steps:
      - name: 🎉 Success Notification
        uses: 8398a7/action-slack@v3
        if: success()
        with:
          status: success
          text: |
            🎉 Nouvelle version déployée avec succès !
            
            **Version**: ${{ needs.release.outputs.version }}
            **Tag**: ${{ needs.release.outputs.tag }}
            **Preview**: ${{ needs.deploy-preview.result == 'success' && 'Déployé avec succès' || 'Déploiement en cours' }}
            
            Voir les [notes de version](https://github.com/${{ github.repository }}/releases/tag/${{ needs.release.outputs.tag }})
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: ❌ Failure Notification
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: failure
          text: |
            ❌ Échec du déploiement de la version ${{ needs.release.outputs.version }}
            
            Vérifiez les logs : ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
